site_name: AcreetionOS Docs
theme:
  name: material
icon:
  favicon: img/acreetionos.ico

docs_dir: docs
nav:
  - Home: index.md
  - The AcreetionOS Philosophy: Why.md
  - Installation Guide: installation.md
  - Calamares Installer Walkthrough: detailed.md
  - Common Problems and Solutions: problems.md
  - Contributing to AcreetionOS: contributing.md
  - AcreetionOS Release Model: releasemodel.md
  - "AcreetionOS: Cinnamon Edition": AcreetionOS-Cinnamon.md

  - Gaming Benchmarking on AcreetionOS: benchmark.md
  - Gaming on AcreetionOS: gaming.md
